/**
 * types/index.ts
 * Global TypeScript types for AuraLearn
 *
 * Sources:
 *  - ARCHITECTURE.md §4 (DB Schema), §5 (JSONB Schemas)
 *  - AI-CONTEXT.md (Tier limits, IRT 1PL rules, Leitner Box rules)
 *  - PRD.md §5 (Functional Requirements)
 *
 * Rules:
 *  - Field names match ARCHITECTURE.md SQL column names exactly (snake_case)
 *  - difficulty_b is float, NOT integer
 *  - difficulty_label is union literal: 'easy' | 'medium' | 'hard'
 *  - Quiz question type is only 'multiple_choice' in v1 (short answer removed from scope)
 *  - Flashcard supports 'front_back' and 'cloze_deletion'
 */

// ─────────────────────────────────────────────
// PRIMITIVES & ENUMS
// ─────────────────────────────────────────────

/** User tier. Stored as TEXT in DB. Default: 'free' */
export type Tier = 'free' | 'pro';

/** Gemini model used for document processing */
export type GeminiModel = 'flash' | 'pro';

/** Difficulty label derived from difficulty_b (IRT 1PL Rasch Model)
 *  b < -0.67 → 'easy'
 *  -0.67 ≤ b ≤ 0.67 → 'medium'
 *  b > 0.67 → 'hard'
 */
export type DifficultyLabel = 'easy' | 'medium' | 'hard';

/** Quiz question type — only MCQ in v1 */
export type QuestionType = 'multiple_choice';

/** Flashcard card type */
export type FlashcardType = 'front_back' | 'cloze_deletion';

/** Chat message role */
export type ChatRole = 'user' | 'assistant';

// ─────────────────────────────────────────────
// DATABASE TABLE TYPES
// Maps 1:1 to ARCHITECTURE.md SQL schema
// ─────────────────────────────────────────────

/**
 * user_profiles table
 * Joined with auth.users via id (UUID).
 */
export interface UserProfile {
  /** UUID — references auth.users(id) */
  id: string;
  /** Subscription tier */
  tier: Tier;
  /** Number of documents processed this month */
  docs_used: number;
  /**
   * Date of last quota reset (monthly).
   * Lazy Evaluation: reset triggered on upload if month has changed.
   * Stored as DATE in DB.
   */
  quota_reset: string; // ISO date string 'YYYY-MM-DD'
  /**
   * IRT 1PL θ (theta) — user ability parameter.
   * Default: 0.0 | Range: typically -3.0 to +3.0
   * Persisted to DB, updated in batch at end of quiz session.
   */
  user_theta: number;
}

/**
 * documents table
 * Stores extracted text only — physical file is NEVER stored.
 */
export interface Document {
  id: string;
  user_id: string;
  /** Original filename or user-defined title */
  title: string | null;
  /** Full extracted text from the document */
  extracted_text: string;
  /** Total number of pages/slides/images processed */
  page_count: number | null;
  /** Which Gemini model was used for extraction */
  model_used: GeminiModel | null;
  created_at: string; // ISO timestamp
}

/**
 * quizzes table
 * Contains JSONB array of questions.
 */
export interface Quiz {
  id: string;
  document_id: string;
  user_id: string;
  /** Array of quiz questions — see QuizQuestion */
  questions: QuizQuestion[];
  created_at: string;
}

/**
 * JSONB schema for a single quiz question (quizzes.questions[])
 * Source: ARCHITECTURE.md §5 + AI-CONTEXT.md Prompt Guidelines
 */
export interface QuizQuestion {
  /** Zero-based index within the quiz */
  idx: number;
  /** Only 'multiple_choice' in v1 */
  type: QuestionType;
  /**
   * IRT 1PL difficulty parameter b.
   * Must be a float between -2.0 (very easy/factual) and +2.0 (very hard/analytical).
   * Generated by Gemini — NEVER an integer.
   */
  difficulty_b: number;
  /** Derived from difficulty_b. See DifficultyLabel. */
  difficulty_label: DifficultyLabel;
  /** The question text */
  question: string;
  /** Exactly 4 answer options */
  options: [string, string, string, string];
  /** The correct answer — must match one of options exactly */
  answer: string;
  /** A verbatim sentence from the source document hinting at the answer */
  source_hint: string;
}

/**
 * flashcard_sets table
 * Contains JSONB array of flashcard cards.
 */
export interface FlashcardSet {
  id: string;
  document_id: string;
  user_id: string;
  /** Array of flashcard cards — see FlashcardCard */
  cards: FlashcardCard[];
  created_at: string;
}

/**
 * JSONB schema for a single flashcard card (flashcard_sets.cards[])
 * Source: ARCHITECTURE.md §5
 * Supports front_back and cloze_deletion types.
 */
export interface FlashcardCard {
  /** Zero-based index within the flashcard set */
  idx: number;
  type: FlashcardType;
  /** Front face content (concept, term, or question) */
  front: string;
  /** Back face content (definition or answer) */
  back: string;
  /**
   * For cloze_deletion cards: the sentence with blanked-out keyword(s).
   * Example: "AuraLearn menggunakan model ___ untuk kuis adaptif."
   * null for front_back type.
   */
  cloze_text: string | null;
  /**
   * Leitner Box position.
   * Range: 1 | 2 | 3
   * - 'Ingat' → move to next box (max 3)
   * - 'Lupa'  → return to box 1
   */
  leitner_box: 1 | 2 | 3;
}

/**
 * share_links table
 * A share link targets EITHER a quiz OR a flashcard set (never both).
 * Enforced by CHECK constraint in DB.
 */
export interface ShareLink {
  /** UUID v4 token — used in URL: /share/[token] */
  token: string;
  /**
   * Linked quiz ID. Mutually exclusive with flashcard_set_id.
   * Exactly one of quiz_id or flashcard_set_id must be non-null.
   */
  quiz_id: string | null;
  /**
   * Linked flashcard set ID. Mutually exclusive with quiz_id.
   * Exactly one of quiz_id or flashcard_set_id must be non-null.
   */
  flashcard_set_id: string | null;
  owner_id: string;
  created_at: string;
}

/**
 * share_attempts table
 * Tracks IP-based rate limiting for share link access.
 * Rate limit: 3 attempts per day per IP per token.
 */
export interface ShareAttempt {
  id: string;
  /** References share_links.token */
  token: string;
  /** Hashed IP address (NOT raw IP) */
  ip_hash: string;
  /** Date of the attempt (YYYY-MM-DD) */
  attempt_date: string;
}

/**
 * flagged_questions table
 * User-submitted reports for ambiguous or irrelevant quiz questions.
 */
export interface FlaggedQuestion {
  id: string;
  quiz_id: string;
  /** Index of the flagged question within quizzes.questions[] */
  question_idx: number;
  /** Nullable — guest users can flag without being logged in */
  user_id: string | null;
  reason: string | null;
  created_at: string;
}

/**
 * chat_sessions table
 * One active session per document per user (frontend policy).
 * Backend schema supports multiple sessions per document.
 */
export interface ChatSession {
  id: string;
  user_id: string;
  document_id: string;
  created_at: string;
}

/**
 * chat_messages table
 * Individual messages within a chat session.
 * Last 20 messages are injected into Gemini system prompt per request.
 */
export interface ChatMessage {
  id: string;
  session_id: string;
  role: ChatRole;
  content: string;
  created_at: string;
}

/**
 * chat_daily_usage table
 * Tracks daily message count for Free tier users.
 * Free limit: 5 messages per day.
 * Pro: unlimited (no row inserted / not checked).
 */
export interface ChatDailyUsage {
  user_id: string;
  /** Date of usage (YYYY-MM-DD) */
  usage_date: string;
  /** Running count of messages sent today */
  msg_count: number;
}

// ─────────────────────────────────────────────
// CLIENT-SIDE / SESSION TYPES
// Not stored in DB — used in React state or sessionStorage
// ─────────────────────────────────────────────

/**
 * Temporary quiz session for Guest users.
 * Stored in sessionStorage, not in DB.
 * Migrated to DB if guest registers within the same browser session.
 */
export interface GuestQuizSession {
  /** Source document title (from file name) */
  document_title: string;
  /** Extracted text — held in memory, sent to Gemini for generation */
  extracted_text: string;
  /** Generated quiz questions */
  questions: QuizQuestion[];
  /** Timestamp of creation */
  created_at: string;
  /** Flag to indicate if the guest session has been migrated to DB */
  migrated: boolean;
}

// ─────────────────────────────────────────────
// API REQUEST / RESPONSE TYPES
// Used by Next.js Route Handlers
// ─────────────────────────────────────────────

/**
 * Result returned from the file parsing + extraction pipeline.
 * Used internally by /api/upload and /api/guest/upload.
 */
export interface UploadResult {
  /** Cleaned and extracted plain text */
  extracted_text: string;
  /** Number of pages/slides/images processed */
  page_count: number;
  /** Which Gemini model was selected for this file */
  model_used: GeminiModel;
  /**
   * Whether the file was detected as a scanned PDF.
   * True if avg chars per page < 50 (heuristic).
   */
  is_scanned_pdf: boolean;
}

/**
 * Request body for POST /api/generate/quiz
 */
export interface GenerateQuizRequest {
  /** document.id — used to fetch extracted_text from DB */
  document_id: string;
  /**
   * Number of questions to generate.
   * Free: max 10 | Pro: max 30
   */
  question_count: number;
}

/**
 * Response from POST /api/generate/quiz
 */
export interface GenerateQuizResponse {
  /** The newly created quiz record */
  quiz: Quiz;
}

/**
 * Request body for POST /api/generate/flashcard
 */
export interface GenerateFlashcardRequest {
  /** document.id — used to fetch extracted_text from DB */
  document_id: string;
  /**
   * Number of cards to generate.
   * Free: max 15 | Pro: max 50
   */
  card_count: number;
}

/**
 * Response from POST /api/generate/flashcard
 */
export interface GenerateFlashcardResponse {
  /** The newly created flashcard set record */
  flashcard_set: FlashcardSet;
}

// ─────────────────────────────────────────────
// TIER LIMIT CONSTANTS
// Source: AI-CONTEXT.md §Batas Tier
// ─────────────────────────────────────────────

export const TIER_LIMITS = {
  free: {
    docs_per_month: 3,
    pages_per_file: 10,
    questions_per_quiz: 10,
    flashcards_per_session: 15,
    chat_messages_per_day: 5,
    can_export_print: false,
    can_explain_question: false,
  },
  pro: {
    docs_per_month: 50,
    pages_per_file: 100,
    questions_per_quiz: 30,
    flashcards_per_session: 50,
    chat_messages_per_day: Infinity,
    can_export_print: true,
    can_explain_question: true,
  },
} as const;

// ─────────────────────────────────────────────
// IRT 1PL RASCH MODEL CONSTANTS
// Source: AI-CONTEXT.md §Adaptive Difficulty Rules
// ─────────────────────────────────────────────

/** IRT learning rate for online gradient descent */
export const IRT_LEARNING_RATE = 0.3;

/** Default theta for new users */
export const IRT_THETA_DEFAULT = 0.0;

/** Difficulty_b range generated by Gemini */
export const IRT_DIFFICULTY_RANGE = {
  min: -2.0,
  max: 2.0,
} as const;

/** Thresholds for deriving difficulty_label from difficulty_b */
export const IRT_DIFFICULTY_THRESHOLDS = {
  easy_max: -0.67,  // b < -0.67 → 'easy'
  hard_min: 0.67,   // b > 0.67  → 'hard'
  // -0.67 ≤ b ≤ 0.67 → 'medium'
} as const;

// ─────────────────────────────────────────────
// LEITNER BOX CONSTANTS
// Source: AI-CONTEXT.md §Leitner Box Rules
// ─────────────────────────────────────────────

export type LeitnerBox = 1 | 2 | 3;

export const LEITNER_REVIEW_INTERVAL: Record<LeitnerBox, number> = {
  1: 1, // Review every round
  2: 2, // Review every 2 rounds
  3: 3, // Review every 3 rounds
};
